# Workflow to publish tagged releases to github packages.
name: Publish package to GitHub Packages

on:
  push:
    tags: release/[0-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
